
[blocks_limit]
	#--------------------------------------------------------------------------
	#The count limit of blocks that are used in block entities. The first para is count limit and the second para is stabilize para.
	blocks_limit = [["create:deployer", 256, 100], ["create:mechanical_drill", 256, 100], ["minecraft:dirt", 2048, 10000], ["create:linear_chassis", 2048, -100], ["minecraft:netherrack", 2048, 5000]]
	#--------------------------------------------------------------------------
	#Whether to log the block entity problem if it can't turned into block entities.
	"Log block entity problem" = false
	#--------------------------------------------------------------------------
	#10x of destroy speed | If you set 14 and will calculate 1.4 as destroy speed 
	#Exp: obsidian is 40 and 400 in this case, dirt is 0.5 and 5 set in this case. 
	#default value is suggested because dirt and sand will drop but stone will stay
	#Range: > 0
	"10% of destroy speed" = 14
	#--------------------------------------------------------------------------
	#The longest XZ distance of block entity | If set 20: 17*42*20 is allowed but 20*42*21 is forbidden.
	#Range: 3 ~ 500
	"block entity max length XZ" = 40
	#--------------------------------------------------------------------------
	#The longest Y  distance of block entity | If set 20: 42*14*42 is allowed but 42*24*42 is forbidden.
	#Range: 3 ~ 500
	"block entity max length Y" = 60
	#--------------------------------------------------------------------------
	#A list of blocks can't be moved and change into block entities.
	blocks_unmoved = ["minecraft:deepslate", "minecraft:stone", "minecraft:cobblestone", "create:belt", "create:mechanical_crafter"]
	#--------------------------------------------------------------------------
	#A list of blocks can't be crushed by block entities. 
	#If you squeeze a stone with dirt and stone in this list the dirt will drop while stone leave!
	blocks_uncrushable = ["minecraft:deepslate", "minecraft:stone", "minecraft:cobblestone"]
	#--------------------------------------------------------------------------
	#A list of blocks can be crushed by block entities.
	#Create's default config.
	#If you squeeze a stone with dirt and stone in this list the stone will drop while dirt leave!
	#If you add fluid, these fluid will vanish like create vanilla
	#Warning:Block burned by lava might be conflict with player,you can add minecraft:lava to avoid block burned by lava!
	blocks_crushable = ["minecraft:water"]
	#--------------------------------------------------------------------------
	#A list of blocks will be ignored by entity control
	#Some block entity use the same func but they have unique method and para.
	#Add all of them in this list will ignore these entity
	#default config compat with Create:big cannon! Just add new block not remove them!  
	#Warning! Make sure these new added block won't with bug!
	blocks_ignore = ["create:piston_extension_pole", "createbigcannons:ap_shot", "createbigcannons:powder_charge", "createbigcannons:ram_head", "createbigcannons:worm_head", "createbigcannons:solid_shot", "createbigcannons:ap_shot", "createbigcannons:mortar_stone", "createbigcannons:bag_of_grapeshot", "createbigcannons:he_shell", "createbigcannons:ap_shell", "createbigcannons:shrapnel_shell", "createbigcannons:fluid_shell", "createbigcannons:smoke_shell"]
	#--------------------------------------------------------------------------
	#When enabled, blocks will calculate the experiment para for block entities.This might take very little time.
	"calculate block stabilize para" = true
	#--------------------------------------------------------------------------
	#The max limit of stabilize para. One normal block have 100 default stabilize count.
	#Set depend on storage box can avoid block entities NBT overflow.
	#Range: > 0
	"block entity max stabilize para" = 204800

