
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.netherexp]
			claret = true
			smokestalk = true

	[types.leaves_type]

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = true
			flowering_acacia = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.stone_type]

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.scguns]
			phosphorite = true

		[types.stone_type.rubinated_nether]
			altar_stone = true

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.windswept]
			shale = true

		[types.stone_type.architects_palette]
			abyssaline = true
			hadaline = true
			myonite = true
			esoterrack = true
			onyx = true
			wardstone = true
			moonshale = true
			nebulite = true

		[types.stone_type.pneumaticcraft]
			reinforced_stone = true
			compressed_stone = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.sob]
			counter = true

		[entries.wood_type.architects_palette]
			boards = true
			board_stairs = true
			railing = true
			board_wall = true
			board_slab = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

	[entries.stone_type]

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

